### PR TITLE
Response serialization issue with BigInt

### PR DESCRIPTION
**Pull request by starrematte**
Fixed a problem in which response of type object/json was unable to correctly JSON.stringify an object with nested property of type BigInt.
The issue resided in the file response.ts:73 as can be seen in the screenshot.
Also tests have been updated for this issue  (file "response_test.ts" at line 84).

Screenshot_issue

Matteo

### CODE REVIEW

**Review by kitsonk — APPROVED** [review]
LGTM

**Review by kitsonk — CHANGES_REQUESTED** [review]
Actually thinking about this a bit more, it is a problem. JSON doesn't support BigInts, and how it gets serialised is really quite implementation specific, as both the producer and receiver have to agree how it is serialised.  Just putting it as a string may not be suitable for a lot of workloads, as people might want to forgo precision and keep coerce it to a `Number` or might want some other mechanism to denote it is a `BigInt` (e.g. replacing `123456n` with `{ __bigInit: "123456" }`.

That being said, serialising all the bodies before they are sent could easily be a pain.  I wouldn't be opposed to having some sort of _JSON.stringify replacer_ option that would be used as the replacer for this problem (as well as cyclical object structure issues).

**Comment by starrematte** [comment]
Well actually you let me to some ideas: 
1. we can still use `JSON.stringify` but instead of converting a value directly to a string we can check if the number exceeds the maximum of an integer `Number.MAX_SAFE_INTEGER - 1` and if it does, converting it to an object as you proposed 
`{_bigInt: value}` (and this idea can be used commonly with every unhandled types if ever there will be: 
`{["_" + typeof unhandledtype]: unhandledtype}`), or if it doesn't converting it as `Integer` (but there will be a precision loss and that's not very good);
2. directly converting it to this `{_bigInt: bigIntValue+"n"}` or this `{["_" + typeof unhandledtype]: unhandledtype}` for the unhandled types;
3. we can replace `JSON.stringify` with a cyclical object type check, using a list of accepted types, and/or the rest will be _stringified_ as this `{["_" + typeof unhandledtype]: unhandledtype}` (except of course for bigInt that will have an "n" appended to the value).
4. we can check the char lenght of the BigInt value and place it together with the cut value itself: `{_bigInt: bigIntValue+"n", charactersLength: someLongInt}` (actually the cut value can be decided by the oak specifics. I do not know if this is the right way to decide something like this).

Of course all of the above don't mention a solution for by taking in consideration the environment specific implementation.
Using string for bigInt values can lead to a some kind of loss considering the "no-arbitrary" length of BigInt (not sure if we can check this on every platform `performance.memory.jsHeapSizeLimit` and `performance.memory.usedJSHeapSize`. But checking and calculating this would led to headaches perhaps (?))

So, considering the simplest idea we can use the `{_bigInt: bigIntValue+"n"}` solution.
Prove me wrong on every solution if needed and thank you very much for the previous answer

**Comment by kitsonk** [comment]
Again, since it requires both the sender and receiver to agree to a non-standard encoding, I don't think it is something that oak should handle directly, as it becomes implementation specific.

Either people who might have bigints in their payloads serialize the body themselves, or at the app options level we provide an optional JSON body replacer and reviver.

**Comment by kitsonk** [comment]
Again, thanks, it is a good idea, but I think we need something like I added in 855ecf04b84c32e3904af8bfe5b687793324b52a where people can just pass their own replacer and reviver as they see fit.

**Pull request closed without merging**
