### PR TITLE
Reduce `50MB.zip` size

### LINKED ISSUE #486: Is vendoring the `50MB.zip` example file necessary?
https://github.com/oakserver/oak/blob/2f45b22b0824b358b3aca0f48c0304633a6b7c50/examples/static/50MB.zip

Git doesn't seem to be able to compress this example file and even doing a shallow clone (`--depth 1`) is downloading the entire 50MB:

```
$ git clone https://github.com/oakserver/oak --depth 1
Cloning into 'oak'...
remote: Enumerating objects: 140, done.
remote: Counting objects: 100% (140/140), done.
remote: Compressing objects: 100% (127/127), done.
remote: Total 140 (delta 8), reused 48 (delta 2), pack-reused 0
Receiving objects: 100% (140/140), 50.39 MiB | 2.05 MiB/s, done.
Resolving deltas: 100% (8/8), done.
```

This is not great for outsider contributor, online IDEs or who just happen to checkout the repo. Would you consider using a example that Git can compress well (if that exists) or put this file outside of the repo?

### PR DESCRIPTION
**Pull request by kidonng**
Resolve #486

This PR replaces `examples/static/50MB.zip` with a file created via `dd if=/dev/zero bs=1024 count=50000 > examples/static/50MB.zip` and can be compressed pretty well by Git.

As long as the example server doesn't enable any compression, this file should be able to still serve its purpose.

```sh
$ git clone https://github.com/kidonng/oak --branch reduce-repo-size --depth 1
Cloning into 'oak'...
remote: Enumerating objects: 140, done.
remote: Counting objects: 100% (140/140), done.
remote: Compressing objects: 100% (127/127), done.
remote: Total 140 (delta 8), reused 47 (delta 2), pack-reused 0
Receiving objects: 100% (140/140), 427.73 KiB | 1.38 MiB/s, done. # Was 50.39 MiB
Resolving deltas: 100% (8/8), done.
```

### CODE REVIEW

**Comment by bodograumann** [comment]
Unfortunately most people won’t do a shallow clone. So this doesn’t change much.

**Comment by kidonng** [comment]
It doesn't do harm to full clone, so why give up the benefits?

**Comment by LeoDog896** [comment]
This is incredibly useful for quick experiments on online IDEs :+1:.

**Review by kitsonk — APPROVED** [review]
LGTM

**Pull request merged**
