### PR TITLE
Updated to std 0.50.0

### LINKED ISSUE #64: std@v1.0.0-rc1 deps missing
Per https://github.com/denoland/deno/issues/5176, the `v1.0.0-rc1` tag on `std` was a mistake ~and one should use `v0.42.0` (with the same Deno version)~.  `v0.50.0` is now up.

### PR DESCRIPTION
**Pull request by olaven**
I believe this would close #64 🦕

### CODE REVIEW

**Comment by kitsonk** [comment]
Sorry, didn't see this. Fixed via 80994ab053989e794eebd49ef812e684f0a517dc

**Comment by olaven** [comment]
@kitsonk No problem! The point is that it is fixed 😄

**Comment by kitsonk** [comment]
`--reload`?

**Comment by olaven** [comment]
Thanks, that was it 😅

**Pull request closed without merging**
