### PR TITLE
ISSUE 352, fix content-length in HTTP/2 Range requests

### PR DESCRIPTION
**Pull request by aperiosio**

### CODE REVIEW

**Comment by aperiosio** [comment]
Hmm, confused, UI says i signed the Contributor License Agreement, did it again....

**Comment by kitsonk** [comment]
The e-mail address used in the commit is not associated with your GitHub account, and therefore GitHub is not attributing the commit to you.

**Comment by aperiosio** [comment]
@kitsonk argh...sorry, yes, was my fault, fixed, thank you.

**Review by kitsonk — APPROVED** [review]
LGTM

**Pull request merged**
